[tool.poetry]
name = "flask-challenge"
version = "0.1.0"
description = ""
authors = ["Pedals"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^3.0.2"
peewee = "^3.17.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
